INSERT INTO `exercises` (`name`, `description`, `body_part_targeted`, `category_type`, `difficulty_level`, `equipment_needed`, `equipment_details`, `image_url`, `video_url`, `gender_target`, `notes`) VALUES
('Push-ups', 'A classic bodyweight exercise that works the chest, shoulders, and triceps. Keep your body straight and lower until your chest nearly touches the floor.', 'Chest', 'Strength', 'Beginner', 0, NULL, 'images/exercises/pushup.jpg', NULL, 'Unisex', 'Ensure proper form to avoid injury. Can be modified by doing them on knees.'),
('Squats (Bodyweight)', 'A fundamental lower body exercise targeting quads, hamstrings, and glutes. Keep your back straight and go as low as comfortable.', 'Legs', 'Strength', 'Beginner', 0, NULL, 'images/exercises/squat.jpg', NULL, 'Unisex', 'Focus on depth and keeping your heels on the ground.'),
('Plank', 'An isometric core strength exercise that involves maintaining a position similar to a push-up for the maximum possible time.', 'Abs', 'Strength', 'Beginner', 0, NULL, 'images/exercises/plank.jpg', NULL, 'Unisex', 'Engage your core and avoid letting your hips sag.'),
('Dumbbell Bench Press', 'A great exercise for building chest, shoulder, and triceps strength using dumbbells on a bench.', 'Chest', 'Strength', 'Intermediate', 1, 'Dumbbells, Flat Bench', 'images/exercises/db_bench_press.jpg', NULL, 'Unisex', 'Control the weight throughout the movement.'),
('Barbell Deadlift', 'A compound exercise that works multiple muscle groups including the back, legs, and glutes. Involves lifting a loaded barbell off the ground.', 'Back', 'Strength', 'Advanced', 1, 'Barbell, Weight Plates', 'images/exercises/deadlift.jpg', NULL, 'Unisex', 'Proper form is crucial to prevent injury. Start with light weight.'),
('Running (Treadmill)', 'Cardiovascular exercise on a treadmill, good for endurance and burning calories.', 'Full Body', 'Cardio', 'Intermediate', 1, 'Treadmill', 'images/exercises/treadmill_running.jpg', NULL, 'Unisex', 'Adjust speed and incline to vary intensity.'),
('Jumping Jacks', 'A full-body calisthenic exercise performed by jumping to a position with the legs spread wide and the hands touching overhead.', 'Full Body', 'Cardio', 'Beginner', 0, NULL, 'images/exercises/jumping_jacks.jpg', NULL, 'Unisex', 'Good for warm-ups.'),
('Pull-ups', 'An upper-body compound pulling exercise where the body is suspended by the hands and pulls up. Primarily targets the latissimus dorsi muscle.', 'Back', 'Strength', 'Advanced', 1, 'Pull-up Bar', 'images/exercises/pullups.jpg', NULL, 'Male', 'Can be assisted with bands if needed. Often considered more challenging for females due to upper body strength distribution, but achievable for all.'),
('Lunges', 'A strength training exercise that can be used to work the quadriceps, hamstrings, glutes, and core muscles.', 'Legs', 'Strength', 'Beginner', 0, NULL, 'images/exercises/lunges.jpg', NULL, 'Unisex', 'Keep your front knee aligned with your ankle.'),
('Bicep Curls (Dumbbell)', 'An isolation exercise that targets the biceps muscles using dumbbells.', 'Biceps', 'Strength', 'Beginner', 1, 'Dumbbells', 'images/exercises/bicep_curls.jpg', NULL, 'Unisex', 'Avoid using momentum; focus on the bicep contraction.'),
('Yoga Sun Salutation', 'A sequence of yoga poses performed in a flowing manner, good for flexibility and a gentle warm-up.', 'Full Body', 'Flexibility', 'Beginner', 0, NULL, 'images/exercises/sun_salutation.jpg', NULL, 'Unisex', 'Coordinate breath with movement.'),
('Leg Press', 'A weight training exercise in which the individual pushes a weight or resistance away from them using their legs.', 'Legs', 'Strength', 'Intermediate', 1, 'Leg Press Machine', 'images/exercises/leg_press.jpg', NULL, 'Unisex', 'Ensure your lower back stays in contact with the seat.'),
('Russian Twists', 'A core exercise that targets the obliques and abdominal muscles. Involves sitting on the floor with knees bent and twisting the torso from side to side.', 'Abs', 'Strength', 'Intermediate', 0, NULL, 'images/exercises/russian_twists.jpg', NULL, 'Unisex', 'Can be done with or without weight.'),
('Shoulder Press (Dumbbell)', 'Targets the deltoid muscles of the shoulders. Can be performed seated or standing.', 'Shoulders', 'Strength', 'Intermediate', 1, 'Dumbbells, Optional Bench', 'images/exercises/shoulder_press.jpg', NULL, 'Unisex', 'Press dumbbells overhead until arms are fully extended.'),
('Glute Bridge', 'A simple but effective exercise for targeting the glutes and hamstrings. Lie on your back with knees bent and lift your hips off the floor.', 'Legs', 'Strength', 'Beginner', 0, NULL, 'images/exercises/glute_bridge.jpg', NULL, 'Female', 'Focus on squeezing the glutes at the top. Often emphasized in female-targeted workouts but beneficial for all.'),
('Tricep Dips (Bench)', 'Uses a bench or elevated surface to work the triceps. Lower your body by bending your elbows.', 'Triceps', 'Strength', 'Intermediate', 1, 'Bench or Sturdy Chair', 'images/exercises/tricep_dips.jpg', NULL, 'Unisex', 'Keep elbows close to your body.'),
('Cycling (Outdoor)', 'Cardiovascular exercise riding a bicycle outdoors. Great for endurance and leg strength.', 'Legs', 'Cardio', 'Intermediate', 1, 'Bicycle, Helmet', 'images/exercises/cycling_outdoor.jpg', NULL, 'Unisex', 'Vary routes and intensity for a better workout.'),
('Calf Raises', 'Targets the calf muscles (gastrocnemius and soleus). Can be done with bodyweight or added weight.', 'Legs', 'Strength', 'Beginner', 0, NULL, 'images/exercises/calf_raises.jpg', NULL, 'Unisex', 'Perform slowly and control the movement.'),
('Lat Pulldown', 'A strength training exercise designed to develop the latissimus dorsi muscle. It performs the functions of downward rotation and depression of the scapulae combined with adduction and extension of the shoulder joint.', 'Back', 'Strength', 'Intermediate', 1, 'Lat Pulldown Machine', 'images/exercises/lat_pulldown.jpg', NULL, 'Unisex', 'Keep your chest up and squeeze your shoulder blades together.'),
('Wall Sit', 'An isometric exercise that primarily targets the quadriceps. Hold a squatting position against a wall.', 'Legs', 'Strength', 'Beginner', 0, NULL, 'images/exercises/wall_sit.jpg', NULL, 'Unisex', 'Aim to hold for increasing durations.'),
('Burpees', 'A full body exercise used in strength training and as an aerobic exercise. Involves a squat, plank, push-up (optional), and jump.', 'Full Body', 'Cardio', 'Intermediate', 0, NULL, 'images/exercises/burpees.jpg', NULL, 'Unisex', 'Maintain a quick pace for cardiovascular benefits. Can be modified by removing the push-up.'),
('Mountain Climbers', 'A dynamic, full-body exercise that increases core strength, agility, and cardiovascular endurance.', 'Abs', 'Cardio', 'Intermediate', 0, NULL, 'images/exercises/mountain_climbers.jpg', NULL, 'Unisex', 'Keep your core engaged and hips low.'),
('Kettlebell Swings', 'A ballistic exercise used to train the posterior chain (hamstrings, glutes, back) in a manner similar to broad jumping.', 'Full Body', 'Strength', 'Intermediate', 1, 'Kettlebell', 'images/exercises/kettlebell_swings.jpg', NULL, 'Unisex', 'Focus on hinging at the hips, not squatting. Keep the back straight.'),
('Overhead Press (Barbell)', 'A compound upper body exercise that targets the shoulders (deltoids), triceps, and core.', 'Shoulders', 'Strength', 'Intermediate', 1, 'Barbell, Weight Plates', 'images/exercises/overhead_press.jpg', NULL, 'Unisex', 'Engage core to protect the lower back. Can be done seated or standing.'),
('Bent-Over Rows (Barbell)', 'A weight training exercise that targets a variety of back muscles, including the lats, rhomboids, and traps.', 'Back', 'Strength', 'Intermediate', 1, 'Barbell, Weight Plates', 'images/exercises/bent_over_rows.jpg', NULL, 'Unisex', 'Keep your back straight and pull the bar towards your lower chest/upper abdomen.'),
('Hanging Leg Raises', 'An advanced core exercise that targets the lower abdominals by lifting the legs while hanging from a pull-up bar.', 'Abs', 'Strength', 'Advanced', 1, 'Pull-up Bar or Captain''s Chair', 'images/exercises/hanging_leg_raises.jpg', NULL, 'Unisex', 'Avoid swinging; control the movement with your abs.'),
('Box Jumps', 'A plyometric exercise that builds explosive power in the legs. Involves jumping onto an elevated platform.', 'Legs', 'Plyometrics', 'Intermediate', 1, 'Plyo Box or Sturdy Platform', 'images/exercises/box_jumps.jpg', NULL, 'Unisex', 'Ensure the box is stable. Land softly.'),
('Walking', 'A low-impact cardiovascular exercise accessible to nearly everyone. Can be done outdoors or on a treadmill.', 'Full Body', 'Cardio', 'Beginner', 0, NULL, 'images/exercises/walking.jpg', NULL, 'Unisex', 'Aim for a brisk pace to elevate your heart rate.'),
('Pilates Hundred', 'A classic Pilates exercise that warms up the body, increases circulation, and builds core strength and endurance.', 'Abs', 'Flexibility', 'Beginner', 0, NULL, 'images/exercises/pilates_hundred.jpg', NULL, 'Unisex', 'Coordinate deep breaths with arm pumps.'),
('Upward-Facing Dog', 'A yoga pose that stretches the chest and spine, and can strengthen the arms and wrists.', 'Back', 'Flexibility', 'Beginner', 0, NULL, 'images/exercises/upward_dog.jpg', NULL, 'Unisex', 'Keep shoulders down and away from ears.'),
('Diamond Push-ups', 'A push-up variation where hands are placed close together, forming a diamond shape, to emphasize triceps activation.', 'Triceps', 'Strength', 'Intermediate', 0, NULL, 'images/exercises/diamond_pushups.jpg', NULL, 'Unisex', 'More challenging than regular push-ups.'),
('Side Plank', 'An isometric exercise that targets the obliques and helps build core stability.', 'Abs', 'Strength', 'Beginner', 0, NULL, 'images/exercises/side_plank.jpg', NULL, 'Unisex', 'Keep your body in a straight line from head to feet. Can be done on forearm or hand.'),
('Hip Thrusts (Barbell)', 'An exercise primarily targeting the glutes, with secondary activation of hamstrings and adductors.', 'Legs', 'Strength', 'Intermediate', 1, 'Barbell, Bench, Padding for Bar', 'images/exercises/hip_thrusts.jpg', NULL, 'Female', 'Focus on glute contraction at the top of the movement. Popular for glute development.'),
('Reverse Flyes (Dumbbell)', 'An exercise targeting the rear deltoids and upper back muscles, promoting better posture.', 'Shoulders', 'Strength', 'Intermediate', 1, 'Dumbbells, Optional Bench', 'images/exercises/reverse_flyes.jpg', NULL, 'Unisex', 'Keep a slight bend in your elbows and squeeze your shoulder blades together.'),
('Farmer''s Walk', 'A strength and conditioning exercise where you hold heavy weights (dumbbells, kettlebells, or specialized handles) and walk for a distance.', 'Full Body', 'Strength', 'Intermediate', 1, 'Heavy Dumbbells or Kettlebells', 'images/exercises/farmers_walk.jpg', NULL, 'Unisex', 'Maintain an upright posture and engage your core and grip strength.');


INSERT INTO `equipments` (`name`, `description`, `category`, `price`, `stock_quantity`, `image_url`, `brand`, `sku`, `specifications`, `is_featured`) VALUES
('Adjustable Dumbbell Set (5-50 lbs)', 'Versatile dumbbell set, perfect for a variety of strength training exercises. Easily adjust weight.', 'Strength Training', 199.99, 50, 'images/equipments/adjustable_dumbbells.jpg', 'ErythroFit', 'DBSET50', 'Material: Cast Iron, Weight Range: 5-50 lbs per dumbbell', 1),
('Premium Yoga Mat (6mm)', 'Extra thick, non-slip yoga mat for comfort and stability during your yoga or pilates sessions.', 'Yoga & Pilates', 29.99, 150, 'images/equipments/yoga_mat_premium.jpg', 'MotionSoul', 'YMATPREM6', 'Material: TPE, Thickness: 6mm, Dimensions: 72" x 24"', 1),
('Foldable Exercise Bike', 'Compact and foldable stationary bike for effective cardio workouts at home. Features multiple resistance levels.', 'Cardio', 149.50, 75, 'images/equipments/foldable_bike.jpg', 'CardioMax', 'EXBIKE001', 'Resistance: Magnetic, Max User Weight: 250 lbs', 0),
('Resistance Band Set (5 Bands)', 'Set of 5 durable resistance bands with varying tension levels for full-body workouts and physical therapy.', 'Accessories', 19.99, 200, 'images/equipments/resistance_bands.jpg', 'ErythroFlex', 'RBSET05', 'Levels: X-Light, Light, Medium, Heavy, X-Heavy', 1),
('Kettlebell (16kg / 35lbs)', 'Solid cast iron kettlebell for dynamic strength and endurance training, including swings, presses, and squats.', 'Strength Training', 45.00, 60, 'images/equipments/kettlebell_16kg.jpg', 'IronCore', 'KB16KG', 'Material: Cast Iron, Weight: 16kg (35 lbs)', 0),
('Speed Jump Rope', 'Lightweight and adjustable speed jump rope for high-intensity cardio, boxing training, and double unders.', 'Cardio', 12.99, 300, 'images/equipments/speed_rope.jpg', 'QuickSkip', 'JROPE01', 'Cable: Steel, Handles: Aluminum, Adjustable Length', 0),
('Foam Roller (High Density)', 'High-density EPP foam roller for muscle recovery, deep tissue massage, and improving flexibility.', 'Accessories', 22.50, 120, 'images/equipments/foam_roller.jpg', 'RecoverWell', 'FRLRHD36', 'Material: EPP Foam, Size: 36" x 6"', 0),
('Weight Bench (Adjustable)', 'Adjustable weight bench for various exercises like bench press, incline press, and dumbbell rows. Folds for storage.', 'Strength Training', 129.00, 40, 'images/equipments/weight_bench_adj.jpg', 'StrongHold', 'WBADJ01', 'Positions: Flat, Incline, Decline, Max Load: 500 lbs', 1),
('Pull-Up Bar (Doorway)', 'Easy-to-install doorway pull-up bar for upper body strength training. No screws required for most door frames.', 'Strength Training', 25.99, 90, 'images/equipments/pullup_bar_door.jpg', 'BarFlex', 'PUBD002', 'Fits doorways 24"-36" wide, Max Weight: 300 lbs', 0),
('Pilates Ring (Magic Circle)', 'Durable fitness ring to add intensity to Pilates workouts, targeting inner and outer thighs, arms, and chest.', 'Yoga & Pilates', 15.75, 110, 'images/equipments/pilates_ring.jpg', 'MotionSoul', 'PRING14', 'Diameter: 14 inches, Padded grips', 0),
('Treadmill (Home Series)', 'Feature-rich treadmill for home use with multiple programs, incline options, and heart rate monitor.', 'Cardio', 599.00, 25, 'images/equipments/treadmill_home.jpg', 'CardioMax', 'TMLHOME05', 'Motor: 2.5 HP, Speed: 0.5-10 MPH, Incline: 0-12%', 1),
('Weightlifting Gloves', 'Padded gloves with wrist support for better grip and hand protection during weightlifting.', 'Accessories', 18.99, 180, 'images/equipments/lifting_gloves.jpg', 'GripStrong', 'GLVWL01', 'Material: Leather & Neoprene, Sizes: S, M, L, XL', 0);


INSERT INTO `equipment_reviews` (`equipment_id`, `user_id`, `rating`, `review_title`, `review_text`, `is_approved`) VALUES
(1, 1, 5, 'Great Dumbbells!', 'These adjustable dumbbells are fantastic and save so much space.', 1),
(1, 2, 4, 'Very versatile', 'Good quality, a bit clunky to adjust sometimes but overall very happy.', 1),
(2, 1, 5, 'Best Yoga Mat Ever', 'So comfortable and truly non-slip. Love the color!', 1);









